services:
  backend:
    build: ./backend ## このディレクトリのbackendのコンテナだから
    ports:
      - "3000:3000" ## Rails標準のポート番号
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" ## コンテナ起動時に実行
    environment:
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true
    volumes:
      - ./backend:/app
      - bundle_data:/usr/local/bundle:cached
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "8000:5173"
  db:
    image: postgres:17
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: user_name
      POSTGRES_PASSWORD: password
      POSTGRES_DB: react_app_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  bundle_data:
  pgdata:
  frontend_node_modules:
  